### PR TITLE
Remove Glide in favor or go modules

### PR DESCRIPTION
**Pull request by khos2ow**
This is to deprecate [Glide](https://github.com/Masterminds/glide) in favor of [go modules](https://github.com/golang/go/wiki/Modules). ~[dep](https://github.com/golang/dep). As stated in [Glide doc](https://github.com/Masterminds/glide#golang-dep):~

~> The Go community now has the dep project to manage dependencies. Please consider trying to migrate from Glide to dep. If there is an issue preventing you from migrating please file an issue with dep so the problem can be corrected. Glide will continue to be supported for some time but is considered to be in a state of support rather than active feature development.~

As discussed with @pdube we're going to use Go Modules instead of dep.

### CODE REVIEW

**Comment by pdube** [comment]
Hey @khos2ow, thanks for looking into this. From what I have been reading, `dep` is also going to be deprecated in favour of using go [modules](https://github.com/golang/go/wiki/Modules). It is in the experimental stage in go 1.11, but should be finalized in v1.12. So, it might not be worth it to migrate to `dep` if we are just going to migrate to modules. What do you think?

**Comment by khos2ow** [comment]
Thanks @pdube, I wasn't aware of that `dep` is being deprecated in favor of something else as well! I'm gonna read more about it. And I agree if they're dropping `dep` or adding `vgo` soon I would say we kill this PR and wait for the other one, otherwise it might make sense to at least to migrate to something newer than Glide for that time-being.

**Comment by pdube** [comment]
Go v1.12beta1 was released 2 days ago, so we might be close to the release

**Comment by khos2ow** [comment]
Nice, so may be we can leave this PR open and circle back to it after new year's holiday and see how it goes then.

**Comment by pdube** [comment]
How strongly do you feel about committing the `vendor` folder?

**Comment by khos2ow** [comment]
A lot! That's the new norm:

- [terraform-providers/terraform-provider-aws](https://github.com/terraform-providers/terraform-provider-aws/tree/master/vendor)
- [kubernetes/kubernetes](https://github.com/kubernetes/kubernetes/tree/master/vendor)
- [hashicorp/terraform](https://github.com/hashicorp/terraform/tree/master/vendor)

**Comment by khos2ow** [comment]
Why should it matter how many LOC there is in the repo? Specially that (when #58 gets through) everything except _vendor_ will be subject of testing, check formatting, etc.

**Comment by khos2ow** [comment]
Once this PR gets merged there won't be any huge PR unless dependency was updated (which technically can be code-reviewed easily but checking `go.mod` and `go.sum`), and technically this should not happen frequently.
Honestly I'm not really concerned about contributor stats and definitely not about maintainability as this will actually make it easier to have consistent builds everywhere (without needing to always keep remembering to update `vendor` folder, if it was gitignored).

**Comment by khos2ow** [comment]
Take hashicorp/terraform#20010 for example, it's not a big PR, and it both updated the functionality and vendor dependency.
I cannot think of a reason why we should not do this, since _big_ projects do.

**Comment by pdube** [comment]
I am not opposing this change. I am merely stating observations

**Comment by pdube** [comment]
I pulled it and it looked like it was building fine. Are you ready to merge it?

**Comment by khos2ow** [comment]
Great, yes I'm good. Let's do this!

**Pull request merged**
